### PR TITLE
Update package.json to use node-openid@1.0

### PR DESCRIPTION
**Pull request by sreuter**
This solves quite some issues with proxies and more. https://github.com/havard/node-openid/pull/135

### CODE REVIEW

**Comment by sreuter** [comment]
Finally, tests are green :+1: !

@jaredhanson, any chance we can get this merged anytime soon? Cheers!

**Comment by sreuter** [comment]
Btw, I highly recommend making this 0.4.0, as there might be regressions for some setups.

**Comment by jaredhanson** [comment]
Can you list what the regressions might be?

**Comment by sreuter** [comment]
The custom http logic in node-openid has been replaced by using request instead. That could potential change behaviour on the redirect following strategy, proxy selection (NO_PROXY is now being honored!), etc.

I don't think there's much risk, but making this a 0.4.0 should make it clear that things should be tested after upgrading.

**Comment by sreuter** [comment]
@jaredhanson Do you have any open concerns with this?

**Comment by sreuter** [comment]
@jaredhanson Would be great to hear if there's anything that prevents us from getting this in. This should make things regarding general openid/http handling much more robust and bullet-proof for the future.

**Comment by jaredhanson** [comment]
Published `passport-openid@0.4.0` to npm.

**Comment by sreuter** [comment]
Awesome sauce, cheers @jaredhanson !

**Comment by mitermayer** [comment]
@sreuter  legendary! :dancer:

**Pull request merged**
